def create_database():
    postgre_database = '''
    DROP TABLE IF EXISTS client cascade;
    DROP TABLE IF EXISTS adm cascade;
    DROP TABLE IF EXISTS kind_of_sport cascade;
    DROP TABLE IF EXISTS gym cascade;
    DROP TABLE IF EXISTS event_t cascade;
    DROP TABLE IF EXISTS client_train;
    DROP TABLE IF EXISTS sport_gym;

    create table client(
        id_client INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        client_password varchar(255) NOT NULL,
        client_name varchar(50) DEFAULT 'NoName',
    	client_login varchar(50) NOT NULL,
    	client_phone varchar(20) NOT NULL,
    	client_text varchar (255)
                    );

    create table adm(
        id_adm INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        adm_email varchar(255) NOT NULL,
        adm_name varchar(50) DEFAULT 'NoName',
    	adm_login varchar(50) NOT NULL,
    	adm_phone varchar(20) NOT NULL,
    	adm_password varchar(255) NOT NULL
                    );


    create table kind_of_sport(
        id_sport INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        sport_name varchar(255) NOT NULL
    				);


    create table gym(
        id_gym INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        gym_name varchar(255) NOT NULL,
    	count_peop int NOT NULL
    				);


    create table event_t(
        numb INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        date_start TIMESTAMP NOT NULL,
    	date_finish TIMESTAMP NOT NULL,
    	id_adm INT NOT NULL,
    	id_sport INT NOT NULL,
    	id_gym INT NOT NULL,
    	FOREIGN KEY (id_adm) REFERENCES adm (id_adm),
    	FOREIGN KEY (id_sport) REFERENCES kind_of_sport (id_sport),
    	FOREIGN KEY (id_gym) REFERENCES gym (id_gym)
    					);

    create table client_train(
        numb INT NOT NULL,
        id_client INT NOT NULL,
    	FOREIGN KEY (numb) REFERENCES event_t (numb),
    	FOREIGN KEY (id_client) REFERENCES client (id_client),
    	PRIMARY KEY (numb, id_client)
    						);

    create table sport_gym(
        id_gym INT NOT NULL,
        id_sport INT NOT NULL,
    	FOREIGN KEY (id_gym) REFERENCES gym (id_gym),
    	FOREIGN KEY (id_sport) REFERENCES kind_of_sport (id_sport),
    	PRIMARY KEY (id_gym, id_sport)
    						);
    '''
    return postgre_database